export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Cart} from "./Cart"
export {default as Checkout} from "./Checkout"
export {default as BookSingle} from "./BookSingle"
export {default as Order} from "./Order"
export {default as OrderSingle} from "./OrderSingle"
export {default as CategorySingle} from "./CategorySingle"

//admin routes
export {default as Dashboard} from "./Admin/Dashboard"
export {default as AdminOrders} from "./Admin/AdminOrders"
export {default as AdminBooks} from "./Admin/AdminBooks"
export {default as AdminUser} from "./Admin/AdminUsers"
export {default as AdminLogin} from "./Admin/AdminLogin"
export {default as AdminMain} from "./Admin/AdminMain"
export {default as BookPost} from "./Admin/BookPost"
export {default as AdminCategory} from "./Admin/AdminCategory"
export {default as BookUpdate} from "./Admin/BookUpdate"